package com.eveningoutpost.dexdrip.cgm.ilet.cloud

import org.junit.Test
import java.math.BigInteger
import java.util.Base64
import java.util.Date
import java.time.Instant

/**
 * Pins the Cognito SRP math against a vector generated by the reference
 * implementation (`pycognito.aws_srp`). The vector uses a fixed client
 * ephemeral `a`, a fixed server `B` and a fixed salt, so any change to the
 * padding, hashing or HKDF order shows up here.
 */
class IletSrpTest {

    private val a = BigInteger("1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef", 16)
    private val b = BigInteger("fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210", 16)

    private val expectedA =
        "15b7895288cf65bac7eb75811c21e9e5d6b0c3616fec42a6f594704b7e4f51b149be77e532e4cd7cfe789e59d87dd41cbe" +
            "22808c1506f2275308d5da8caa45d67149d8443940fed8b8de745c5f0423b011f40e30c46a4144b3efff5b63c565e8f6" +
            "fe9bda16ca3e5c7f52675c32e311e826308995bffa395c562600441efbce9e6e8efd9abbb0b3840df6e713e8d1ebdb64" +
            "e4aa12e51e4ec02412b7ab79962bbd3ffa34160bb55e4a266fe7cf1098596e96d25a17d50434d09c608fd68a3f3d72f3" +
            "260ef630a96440503703c9ec3df24f17f6d5838b31b628bf36748d91565aadce9488e5926dd5774b7d86dfe651063b46" +
            "e1933463297462257822a01d879e113bb2bb28bd4263fff5b110dcbbd5f228cd390cd81f93e7c0bed9d4eafe30a5e846" +
            "ebff974064bb7c64a31f37f9789a26d8c48d6ad05ac735313b53457e4a9cfbffba3a34f8d910da327a5ed5c9279bd224" +
            "6f8a8bd45bfa04d9b4e674f0539b810d17cc15610e747c89cc94d3058affb47bfed7f7da4e6ccc8a4b3ca5367a2ecf"
    private val expectedB =
        "ab099e5c092cc7019e4f42be006b180ed143183daf6cb37ae6680ea1ccc53ac3e3c730d148fb75b25d1d62fa2e40ab34" +
            "f484b5982d86ed3c9ae6acc0250f5cb4b16ecbba54ab68c1979848a182d43cd44f9359136cd00ede3728781f6acb3e9e" +
            "9d81a59edf4449c1319b521a18b7409f73cfa377dbe2fecb7212f8e05a55c22c363cef6dc108f4a6b8c8de67048e0057" +
            "ed218569313f737f3bc12bbbeedfc311adae78db203a2ac4193525f00c741dc523afa6a215f4214d7567508a486ee91d" +
            "733284fe3ceac112701e6bf4d91020e2a4ecfc072b412a631c386aed9ce474a14c289e7ad9bcd4312e205fba7612779f" +
            "c8664835bdd4abcbf0035040212b9881d1816300a982458736ee2deee784e9ab435af2b11cf6d3e5d69d5f04f475b3e0" +
            "c298920bb2f5c1b2d97db7dd4b07e0ca43982075e80aa4025a1e207cded1dd0b2eae7073bce9d803aef7ee1994571169" +
            "6b9e02a0423f698b91f3361cea2bebd891a52011c5d2803642ddbf8a7e2ac09937a9433232c9223c71ad9ae8c156c000"
    private val expectedU = "62433f3a7b26c2addc2dc7a1e290b4cd9d71e7d2ee61c1b4ae47c6346764961e"
    private val expectedHkdf = "1c408abfd83592293c0542e9c3d6317c"
    private val expectedSignature = "sPimnQpxTM5RmTb3a88qJjrL7+p6ZUi87w97VAo1c3k="

    private val poolId = "us-east-2_HNbbVuwO8"
    private val poolName = "HNbbVuwO8"

    @Test
    fun srpMathMatchesReference() {
        val srp = IletSrp(a)
        check(srp.longToHex(srp.largeA) == expectedA) { "A mismatch" }

        val bigA = BigInteger(expectedA, 16)
        val bigB = BigInteger(expectedB, 16)
        check(srp.longToHex(srp.calculateU(bigA, bigB)) == expectedU) { "U mismatch" }

        val hkdf = srp.deriveKey(
            username = "TEST_USER_ID",
            password = "hunter2",
            poolName = poolName,
            serverB = bigB,
            saltHex = "0102030405060708090a0b0c0d0e0f10",
        )
        check(hkdf.joinToString("") { "%02x".format(it) } == expectedHkdf) {
            "HKDF mismatch: ${hkdf.joinToString("") { "%02x".format(it) }}"
        }
    }

    @Test
    fun passwordClaimSignatureMatchesReference() {
        val srp = IletSrp(a)
        val bigB = BigInteger(expectedB, 16)
        val hkdf = srp.deriveKey(
            username = "TEST_USER_ID",
            password = "hunter2",
            poolName = poolName,
            serverB = bigB,
            saltHex = "0102030405060708090a0b0c0d0e0f10",
        )
        val timestamp = "Thu Oct 1 02:00:00 UTC 2026"
        val secretBlock = hex("00112233445566778899aabbccddeeff")
        val msg = poolName.toByteArray(Charsets.UTF_8) +
            "TEST_USER_ID".toByteArray(Charsets.UTF_8) +
            secretBlock +
            timestamp.toByteArray(Charsets.UTF_8)
        val signature = Base64.getEncoder().encodeToString(IletCognitoAuth.hmac(hkdf, msg))
        check(signature == expectedSignature) { "signature mismatch: $signature" }
    }

    @Test
    fun cognitoTimestampFormat() {
        val date = Date.from(Instant.parse("2026-10-01T02:00:00Z"))
        check(IletCognitoAuth.cognitoTimestamp(date) == "Thu Oct 1 02:00:00 UTC 2026") {
            IletCognitoAuth.cognitoTimestamp(date)
        }
    }

    @Test
    fun poolNameMatchesReference() {
        check(poolId.split("_")[1] == poolName)
    }

    private fun hex(value: String): ByteArray {
        val out = ByteArray(value.length / 2)
        for (i in out.indices) out[i] = value.substring(i * 2, i * 2 + 2).toInt(16).toByte()
        return out
    }
}
